### ISSUE TITLE
1.9.4 en_US.lang - correction

### ISSUE THREAD

**Issue by TOLoneWolf** [gigaherz/PackingTape#1]
In PackingTape-1.9.4-0.5.1 the block name is showing tile.packingtape.packagedBlock.name .
change this:
tile.packingtape.packedBlock.name=Packaged Block
to this:
tile.packingtape.packagedBlock.name=Packaged Block
to fix it.

Thank you.

**Comment by gigaherz** [comment]
Nice catch!

**Comment by gigaherz** [comment]
Fixed in 0.5.2  :)
