### ISSUE TITLE
Cannot unpack Iron Chest

### ISSUE THREAD

**Issue by remeisigma** [gigaherz/PackingTape#10]
The Iron Chests from [this mod](https://minecraft.curseforge.com/projects/iron-chests) can be packed, but not unpacked - a tooltip appears saying that the chest cannot be unpacked in this location, regardless where I put it.

**Comment by gigaherz** [comment]
'>_< I'll take a look after I get home. Although if it's what I think it is, I'll poke the Iron Chests people to implement that function correctly... ;P

**Comment by gigaherz** [comment]
v0.7.3 is being reviewed and will be available in a few minutes.
