### ISSUE TITLE
[Resource] es_ES/MX translation

### ISSUE THREAD

**Issue by Dorzar** [gigaherz/PackingTape#12]
//Translate by: Dorzar / VeryHardChamp
//Última actualización: 23/07/2017
tile.packingtape.packaged_block.name=Bloque empaquetado
item.packingtape.tape.name=Cinta de embalaje
text.packingtape.tape.requires_paper=¡Requiere papel para trabajar!

**Comment by gigaherz** [comment]
I have just added this to my development environment, next release will have the language included. Thanks!
