### ISSUE TITLE
Use ore dictionary

### ISSUE THREAD

**Issue by TheRandomLabs** [gigaherz/PackingTape#14]
The recipe should use the ore dictionary.

**Comment by gigaherz** [comment]
Ah right, we have "stock" oredict names for those things now. I believe when I started the mod, they weren't there yet, but yes, good idea.

**Comment by gigaherz** [comment]
Note that I will not be able to get to this immediately, so you can use CraftTweaker to manually add a recipe using oredict.

**Comment by TheRandomLabs** [comment]
I'll just make a pull request. I was too tired to do it last night.
