### ISSUE TITLE
Duplication Glitch[May be Old]

### ISSUE THREAD

**Issue by Flamebom** [gigaherz/PackingTape#19]
Shift right clicking a storage drawer with packing tape **from this mod** pushes out all current items in the drawer into the world, while still retaining its inventory when right clicked again. 

Version: Sky Factory 3 version

**Comment by gigaherz** [comment]
I will take a look as soon as I can, but chances are it's something I fixed locally, but I never released. >_<

**Comment by MentalMouse** [comment]
I didn't get that particular bug but your packing tape didn't seem to work too well with Storage Drawers; they came out with weird orientations and other problems I can't recall now (I think I reported them then).
