### ISSUE TITLE
Dupe with Sponge

### ISSUE THREAD

**Issue by ghost** [gigaherz/PackingTape#2]
Issue: https://github.com/SpongePowered/SpongeForge/issues/823

Not sure who's at fault here, but thought it might be worth cross-posting here for any extra information or potentially a fix.

Thanks!

**Comment by gigaherz** [comment]
Just as a headsup, I just released an update, but it does NOT change this issue. A workaround is being looked at, by the Sponge people.

**Comment by bloodmc** [comment]
@gigaherz This has been resolved in commits
https://github.com/SpongePowered/SpongeCommon/commit/95817e85cf96839cd41ca9fa2bc4c8b2d8ad1c3f
https://github.com/SpongePowered/SpongeForge/commit/cd93a33694fe093e6f6727b0ad4b8e75e78aeda7

**Comment by gigaherz** [comment]
Awesome!
