### ISSUE TITLE
[1.13.2] Crash On Server Load

### ISSUE THREAD

**Issue by Morpheus1101** [gigaherz/PackingTape#20]
Mod Causes Crash on server load 
[crash-2019-02-16_08.19.55-server.txt](https://github.com/gigaherz/PackingTape/files/2871080/crash-2019-02-16_08.19.55-server.txt)

**Comment by gigaherz** [comment]
This is not my mod, but rather a known crash in dedicated servers.

**Comment by gigaherz** [comment]
Actually reading it again, it's not the same issue I was thinking of. This is a crash trying to display the crash. So it could still be my fault.

**Comment by gigaherz** [comment]
I can't reproduce the crash in development, and I can't connect with a client due to https://github.com/MinecraftForge/MinecraftForge/issues/5469

Will keep open until more information is available.

**Comment by Morpheus1101** [comment]
Any further info on this one since the Forge Issue is fixed

**Comment by gigaherz** [comment]
Does the crash still happen? If so I'll retest.
