### ISSUE TITLE
Packing Tape Config has no whitelist

### ISSUE THREAD

**Issue by Jwilson106** [gigaherz/PackingTape#24]
I was trying to use the mod in Enigmatica 5 on MC 1.15 and when I used the tape on a chest it would only open the chest it wouldn't tape it up. 

Found the config file packingtape-server in the default config file and when I opened it the whitelist and blacklist both are empty of tags.

![15906513899038112804062314983669](https://user-images.githubusercontent.com/63497105/83112650-596da180-a07b-11ea-9f7b-160258ae8981.jpg)

**Comment by gigaherz** [comment]
In order to tape a chest you have to sneak-click on it. 
The whitelist being empty is completely normal.  It's purpose is to force-enable blocks that are normally disallowed, such as mob spawners.
