### ISSUE TITLE
Packed Item Disappearing When Right clicking to unpack. Version 1.18

### ISSUE THREAD

**Issue by DSAH1997** [gigaherz/PackingTape#27]
Version - PackingTape-1.18-0.12.1

**Comment by DSAH1997** [comment]
Now what ever storage I unpack It seems to work but the items are no longer in there but it duplicated/glitches what ever is in my inventory into the storage I unpacked

**Comment by gigaherz** [comment]
I'll take a look.

**Comment by DSAH1997** [comment]
Thank you, appreciate it

**Comment by DSAH1997** [comment]
sorry forgot to post it but the last issue is with the prior version on 1.18 (0.12.0)

**Comment by gigaherz** [comment]
Uhh ... you really should update then.

Look at the changelog for 0.12.1 :P

> Fix issue where packaged blocks didn't contain the block entity data.
> 
> Fix issue where the packaged blocks lost their content when reloading from disk.

**Comment by DSAH1997** [comment]
the issue I reported about it disappearing was on that version so I tried backdating to the prior version but it still didn't work, that when I mention about the items disappearing and my inventory glitching into the unpacked storage.

**Comment by gigaherz** [comment]
I think I found the issue. 0.12.2 will be on its way to curseforge as soon as I test it. I will require forge 38.0.14 or newer, since a related issue was fixed there.

**Comment by DSAH1997** [comment]
Yeah that's fine, Thank you
