### ISSUE TITLE
Storage Drawer Controller

### ISSUE THREAD

**Issue by Lunchington** [gigaherz/PackingTape#3]
If you try and apply tape a storage drawer controller it crashes he server. Obviously I didn't do this on purpose but it happens every time :D

**Comment by gigaherz** [comment]
Interesting. Thanks for the report, I'll take a look. Meanwhile, you may want to blacklist the controller's tileentity in your config. ;p

**Comment by gigaherz** [comment]
Do you have a crash log? I'm having troubles reproducing the crash.

**Comment by Lunchington** [comment]
It has been blacklisted. 

I will get one sometime today (not home), i also had a few other variables that might contribute. 

External Storage set to priority 10 from Refined Storage, multiple drawers, and compacting drawers that were locked and concealed. Feeding into the system directly through a chest and import bus (with stack upgrade).
