### ISSUE TITLE
Packing a entity with only one packing tape in hand uses up the hole packing tape

### ISSUE THREAD

**Issue by khazenor** [gigaherz/PackingTape#38]
# Versions
- Minecraft 1.21
- Neoforge 21.0.167
- PackingTape-1.21-0.15.3
- Other mods were installed (modpack https://legacy.curseforge.com/minecraft/modpacks/farming-crossing-5-made-to-order/files/5877488)
# Steps
1. place a chest
2. cheat in a packing tape and pack the chest
3. The entire packing tape gets used up
4. place another chest
5. cheat in two packing tapes and stack them together
6. pack the chest
7. The player still have 2 packing tapes with one of the packing tape now has damage marked on it

# Expected behavior
- The two instances of the packing behavior should match.

**Comment by gigaherz** [comment]
Fixed in 1.21.1-0.15.5 and 1.21.3-0.16.0.
