### ISSUE TITLE
Using a stack of packing tape used durability from all of them.

### ISSUE THREAD

**Issue by MentalMouse** [gigaherz/PackingTape#5]
When "using" a stack of unused packing tape, I'd expect one of them to be chipped off and its durability decremented, similarly to when filling buckets from a stack. Instead, the whole stack gets its durability decremented.

**Comment by gigaherz** [comment]
Strange... it's not supposed to happen that way... I remember coding it to work "like buckets"... I'll take a look as soon as I can.

**Comment by MentalMouse** [comment]
More info: This was in 1.11.2, mod version 0.6.2
