### ISSUE TITLE
[1.12] Crash with ~50 mods :(

### ISSUE THREAD

**Issue by Migmag789** [gigaherz/PackingTape#7]
Hi ! I have a crash with your mod :/
[crash-2017-06-15_18.09.23-client.txt](https://github.com/gigaherz/PackingTape/files/1078258/crash-2017-06-15_18.09.23-client.txt)

**Comment by gigaherz** [comment]
The issue was unrelated to the 50 mods. I just didn't implement the recipe as a JSON file yet, so it was incompatible with forge 2323+. Version 0.6.3 is being reviewed at curseforge as I write this.

**Comment by Migmag789** [comment]
Okay thank you ^^
