### ISSUE TITLE
New Forge versions for 1.12 are breaking mod compatibility, including Packing Tape.

### ISSUE THREAD

**Issue by Zarepheth** [gigaherz/PackingTape#9]
Using the newest Forge versions for Minecraft 1.12 seems to break a number of mods. At the moment, Packing Tape is the one whose error details appear in the log file (note, there are about a half-dozen mods mentioned as failing...)

Minecraft 1.12
Forge 14.21.0.2359 (through the problem exists back to ....2348)
Packing Tape 0.7.0

```
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Packing Tape (packingtape)
Caused by: java.lang.NoClassDefFoundError: gigaherz/packingtape/tape/ItemTape
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:552)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
        ...
```

[Paste.ee Log File](https://paste.ee/p/Ovu2y)

**Comment by gigaherz** [comment]
0.7.0 was compiled with 2359, so I'm not sure where the issue comes from... I'll ask around

**Comment by gigaherz** [comment]
My bad, I uploaded an incomplete jar! I'll reupload on curseforge.

**Comment by gigaherz** [comment]
v0.7.1 is being reviewed and will be available soon. Thanks for reporting!

**Comment by Zarepheth** [comment]
You should check your other mods as well. Toolbelt and Guide Book are also failing - probably for the exact same reason.
_(One might want the Forge developers to retain binary compatibility with older mod versions...)_

**Comment by gigaherz** [comment]
Yes those mods I haven't ported yet to the latest version, but it's 00:45 and I'm far too tired, so I'll update those tomorrow.

And regarding compatibilty: Forge builds before the first recommended build are considered incomplete and the API isn't ensured to remain stable, so it's our fault for releasing mods, and for using them. After Forge releases a Recommended Build is when backward compatibility is a concern.

**Comment by gigaherz** [comment]
ToolBelt and Guidebook have now also been updated. Enjoy! :)

**Comment by Zarepheth** [comment]
Forge is updating faster than modders can keep up.
Guidebook is failing with Forge 14.21.0.2367 - I'm not sure about ToolBelt, I've not yet got the game loaded with Forge greater than 14.21.0.2347 or mods updated for newer versions of Forge.

**Comment by gigaherz** [comment]
I have released new versions of this mod and the rest, compiled with the latest forge. The crashes should be fixed.
